const updateEndorsementsArray = (oldArray) => {
    return oldArray.map(item => ({
        value: item.split(' - ')[0],
        label: item,
        details: item.split(' - ')[1],
    }))
}

const endorsementsArray = [
    'AC10 - Failing to stop after an accident',
    'AC20 - Failing to give particulars or to report an accident within 24 hours',
    'AC30 - Undefined accident offences',
    'BA10 - Driving while disqualified by order of Court',
    'BA30 - Attempting to drive while disqualified by order of Court',
    'BA40 - Causing death by driving while disqualified',
    'BA60 - Causing serious injury by driving while disqualified',
    'CD10 - Driving without due care and attention',
    'CD20 - Driving without reasonable consideration for other road users',
    'CD30 - Driving without due care and attention/reasonable consideration',
    'CD33 - Causing serious injury by careless or inconsiderate driving',
    'CD40 - Causing death through careless driving when unfit through drink',
    'CD50 - Causing death by careless driving when unfit through drugs',
    'CD60 - Causing death by careless driving when alcohol level above limit',
    'CD70 - Causing death by careless driving then failing to supply a specimen for alcohol analysis',
    'CD80 - Causing death by careless, or inconsiderate, driving',
    'CD90 - Causing death by driving: unlicensed, disqualified or uninsured drivers',
    'CU10 - Using a vehicle with defective brakes',
    'CU20 - Causing or likely to cause danger by reason of use of unsuitable vehicle or using a vehicle with parts or accessories (excluding brakes, steering or tyres) in a dangerous condition',
    'CU30 - Using a vehicle with defective tyre(s)',
    'CU40 - Using a vehicle with defective steering',
    'CU50 - Causing or likely to cause danger by reason of load or passengers',
    'CU80 - Breach of requirements as to control of the vehicle, mobile telephone etc.',
    'DD10 - Causing serious injury by dangerous driving',
    'DD40 - Dangerous Driving',
    'DD60 - Manslaughter or culpable homicide while driving a vehicle',
    'DD80 - Causing death by dangerous driving',
    'DD90 - Furious driving',
    'DR10 - Driving or attempting to drive with alcohol concentration above limit',
    'DR20 - Driving or attempting to drive when unfit through drink',
    'DR30 - Driving or attempting to drive then refusing to provide a specimen',
    'DR31 - Driving or attempting to drive then refusing to give permission for analysis of a blood sample that was taken without consent due to incapacity',
    'DR40 - In charge of a vehicle while alcohol level above limit',
    'DR50 - In charge of a vehicle while unfit through drink',
    'DR60 - Failure to provide a specimen for analysis in circumstances other than driving or attempting to drive',
    'DR61 - Refusing to give permission for analysis of a blood sample that was taken without consent due to incapacity in circumstances other than driving or attempting to drive',
    'DR70 - Failing to provide specimen for breath test',
    'DG10 - Driving or attempting to drive with drug level above the specified limit',
    'DG40 - In charge of a vehicle while drug level above specified limit',
    'DG60 - Causing death by careless driving with drug level above the limit',
    'DR80 - Driving or attempting to drive when unfit through drugs',
    'DR90 - In charge of a vehicle when unfit through drugs',
    'IN10 - Using a vehicle uninsured against third party risks',
    'LC20 - Driving otherwise than in accordance with a license',
    'LC30 - Driving after making a false declaration about fitness when applying for a license',
    'LC40 - Driving a vehicle having failed to notify a disability',
    'LC50 - Driving after a license has been revoked or refused on medical grounds',
    'MS10 - Leaving a vehicle in a dangerous position',
    'MS20 - Unlawful pillion riding',
    'MS30 - Playstreet Offense',
    'MS50 - Motor racing on the highway',
    'MS60 - Offences not covered by other codes (including offences relating to breach of requirements as to control of vehicle)',
    'MS70 - Driving with uncorrected defective eyesight',
    'MS80 - Refusing to submit to an eyesight test',
    'MS90 - Failing to give information as to identity of driver etc.',
    'MW10 - Contravention of Special Roads Regulations (excluding speed limits)',
    'PC10 - Undefined contravention of Pedestrian crossing Regulations',
    'PC20 - Contravention of Pedestrian crossing Regulations with moving vehicle',
    'PC30 - Contravention of Pedestrian crossing Regulations Stationary vehicle',
    'SP10 - Exceeding goods vehicle speed limit',
    'SP20 - Exceeding speed limit for type of vehicle (excluding goods or passenger vehicles)',
    'SP30 - Exceeding statutory speed limit on a public road',
    'SP40 - Exceeding passenger vehicle speed limit',
    'SP50 - Exceeding speed limit on a motorway',
    'TS10 - Failing to comply with traffic light signals',
    'TS20 - Failing to comply with double white lines',
    'TS30 - Failing to comply with a "Stop" sign',
    'TS40 - Failing to comply with directions of a constable/traffic warden',
    'TS50 - Failing to comply with traffic sign (excluding "stop" signs, traffic lights or double white lines)',
    'TS60 - Failing to comply with a school crossing patrol sign',
    'TS70 - Undefined failure to comply with a traffic direction sign',
    'TT99 - Disqualified for having more than 12 points in the "totting up" process',
    'UT50 - Aggravated taking of a vehicle',
]

const endorsements = updateEndorsementsArray(endorsementsArray);

export default endorsements;

