export const arnieMcVeighty = {
    //CREATE
    id: 123456,
    industry: 'Driving',
    owner: '#5',
    firstName: 'Arnie',
    middleNames: '',
    lastName: 'McVeighty',
    dateOfBirth: '1990-06-19',
    gender: 'Male',
    email: 'mcveighty.a@gmail.com',
    number: '07590 732 466',
    profile: '50%',
    status: 'Active',
    // PRIMARY QUESTIONS
    nationality: 'British',
    access: [
        '#1',
        '#5', 
    ],
    contactPref: [
        'Email',
    ],
    address1: '44 Gainsbrook Crescent',
    address2: '',
    address3: '',
    cityTown: 'Norton Canes',
    county: '',
    postCode: 'WS11 9TN',
    movedIn: '2021-11-01',
    niNumber: 'AM190690M',
    permitNeeded: 'Yes',
    workPermit: 'EU settled status',
    permitShareCode: 'WF4 84G W16',
    permitNumber: 'WD-584DE78-PP',
    permitExpiry: '2025-11-01',
    criminalConvictions: 'No',
    criminalConvictionsDetails: '',
    //Preference Questions
    startDate: '2023-05-30',
    commuteType: 'Own car',
    travelForWork: '',
    ppeOwned: [
        'HiViz',
    ],
    minPay: '',
    smoker: 'Yes', 
    weekDays: [],
    shifts: [],
    startWindow: '00:00-04:00',
    heardOfUs: '',
    heardOfUsOther: '',
    //MEDICAL QUESTIONS
    diabetes: 'No',
    diabetesYes: '',
    heartCirculatory: 'No',
    heartCirculatoryYes: '',
    stomachIntestinal: 'No',
    stomachIntestinalYes: '',
    difficultySleeping: 'No',
    difficultySleepingYes: '',
    chronicChestNight: 'No',
    chronicChestNightYes: '',
    conditionMedicationTime : 'No',
    conditionMedicationTimeYes: '',
    conditionMealsTime: 'No',
    conditionMealsTimeYes: '',
    mentalHealthNights: 'No',
    mentalHealthNightsYes: '',
    otherConditionsNight: 'No',
    otherConditionsNightYes: '',
    expectingMother: 'No',
    expectingMotherYes: '',
    nightCauseIllness: 'No',
    nightCauseIllnessYes: '',
    OHADiscussion: 'No',
    medicalAgreementTimestamp: '',
    //SKILLS
    trailers: [],
    gearboxes: [],
    loads:[],
    certificates: [],
    workCriteria: [],
    otherVehicles: [],
}

export const danMilverton = {
    id: 987654,
    firstName: 'Daniel',
    middleNames: 'James',
    lastName: 'Milverton',
    owner: '#5',
    number: '07718 478 634',
    email: 'djmilverton@yahoo.com',
    profile: '20%',
    status: 'Active',
    industry: 'Driving',
    dateOfBirth: '1990-01-12',
    gender: 'Male',
    nationality: 'British',
    access: [
        '#1',
        '#5', 
    ],
    contactPref: [
        'Mobile',
        'Email',
    ],
    address1: '34 Roosevelt Apartments',
    address2: '1 Lexington Gardens',
    address3: '',
    cityTown: 'Birmingham',
    county: '',
    postCode: 'B15 2DU',
    movedIn: '2017-12-22',
    niNumber: 'DM120190M',
    permitNeeded: 'No',
    criminalConvictions: 'Yes',
    criminalConvictionsDetails: '',
}

export const jamieFranks = {
    id: 135806,
    firstName: 'Jame',
    middleNames: '',
    lastName: 'Franks',
    owner: '#5',
    number: '07770 597 594',
    email: 'jamie@alliance-personnel.com',
    profile: '34%',
    status: 'Active',
    industry: 'Industrial',
    dateOfBirth: '1980-05-01',
    gender: 'Male',
    nationality: 'British',
    access: [
    ],
    contactPref: [
    ],
    address1: '34 Roosevelt Apartments',
    address2: '1 Lexington Gardens',
    address3: '',
    cityTown: 'Birmingham',
    county: '',
    postCode: 'B15 2DU',
    movedIn: '2017-12-22',
    niNumber: 'DM120190M',
    workPermit: 'Not Needed',
    criminalConvictions: 'No',
    criminalConvictionsDetails: '',
}

export const amiKaur = {
    //CREATE
    id: 756398,
    industry: 'Industrial',
    owner: '# 1',
    firstName: 'Ami',
    middleNames: '',
    lastName: 'Kaur',
    dateOfBirth: '1990-06-19',
    gender: 'Female',
    email: 'ami@alliance-personnel.com',
    number: '07766 597 594',
    profile: '50%',
    status: 'Active',
    // PRIMARY QUESTIONS
    nationality: '',
    access: [
        '#1'
    ],
    contactPref: [
        'Email'
    ],
    address1: '',
    address2: '',
    address3: '',
    cityTown: '',
    county: '',
    postCode: '',
    movedIn: '',
    niNumber: '',
    permitNeeded: '',
    workPermit: '',
    permitShareCode: '',
    permitNumber: '',
    permitExpiry: '',
    criminalConvictions: '',
    criminalConvictionsDetails: '',
    //Preference Questions
    startDate: '',
    commuteType: '',
    travelForWork: '',
    ppeOwned: [],
    minPay: '',
    smoker: '', 
    weekDays: [],
    shifts: [],
    startWindow: '',
    heardOfUs: '',
    heardOfUsOther: '',
    //MEDICAL QUESTIONS
    diabetes: '',
    diabetesYes: '',
    heartCirculatory: '',
    heartCirculatoryYes: '',
    stomachIntestinal: '',
    stomachIntestinalYes: '',
    difficultySleeping: '',
    difficultySleepingYes: '',
    chronicChestNight: '',
    chronicChestNightYes: '',
    conditionMedicationTime : '',
    conditionMedicationTimeYes: '',
    conditionMealsTime: '',
    conditionMealsTimeYes: '',
    mentalHealthNights: '',
    mentalHealthNightsYes: '',
    otherConditionsNight: '',
    otherConditionsNightYes: '',
    expectingMother: '',
    expectingMotherYes: '',
    nightCauseIllness: '',
    nightCauseIllnessYes: '',
    OHADiscussion: '',
    medicalAgreementTimestamp: '',
    //SKILLS
    trailers: [],
    gearboxes: [],
    loads:[],
    certificates: [],
    workCriteria: [],
    otherVehicles: [],
}