export const arnieMcVeighty = {
    id: 123456,
    firstName: 'Arnie',
    middleNames: '',
    lastName: 'McVeighty',
    owner: '#5',
    number: '07590 732 466',
    email: 'mcveighty.a@gmail.com',
    profile: '50%',
    status: 'Active',
    industry: 'Driving',
    dateOfBirth: '1990-06-19',
    gender: 'Male',
    nationality: 'British',
    access: [
        '#1',
        '#5', 
    ],
    contactPref: [
        'Email',
    ],
    address1: '44 Gainsbrook Crescent',
    address2: '',
    address3: '',
    cityTown: 'Norton Canes',
    county: '',
    postCode: 'WS11 9TN',
    movedIn: '2021-11-01',
    niNumber: 'AM190690M',
    permitNeeded: 'Yes',
    workPermit: 'EU settled status',
    permitShareCode: 'WF4 84G W16',
    permitNumber: 'WD-584DE78-PP',
    permitExpiry: '2025-11-01',
    criminalConvictions: 'No',
    criminalConvictionsDetails: '',
}

export const danMilverton = {
    id: 987654,
    firstName: 'Daniel',
    middleNames: 'James',
    lastName: 'Milverton',
    owner: '#5',
    number: '07718 478 634',
    email: 'djmilverton@yahoo.com',
    profile: '20%',
    status: 'Active',
    industry: 'Driving',
    dateOfBirth: '1990-01-12',
    gender: 'Male',
    nationality: 'British',
    access: [
        '#1',
        '#5', 
    ],
    contactPref: [
        'Mobile',
        'Email',
    ],
    address1: '34 Roosevelt Apartments',
    address2: '1 Lexington Gardens',
    address3: '',
    cityTown: 'Birmingham',
    county: '',
    postCode: 'B15 2DU',
    movedIn: '2017-12-22',
    niNumber: 'DM120190M',
    permitNeeded: 'No',
    criminalConvictions: 'Yes',
    criminalConvictionsDetails: '',
}

export const jamieFranks = {
    id: 135806,
    firstName: 'Jame',
    middleNames: '',
    lastName: 'Franks',
    owner: '#5',
    number: '07770 597 594',
    email: 'jamie@alliance-personnel.com',
    profile: '34%',
    status: 'Active',
    industry: 'Industrial',
    dateOfBirth: '1980-05-01',
    gender: 'Male',
    nationality: 'British',
    access: [
    ],
    contactPref: [
    ],
    address1: '34 Roosevelt Apartments',
    address2: '1 Lexington Gardens',
    address3: '',
    cityTown: 'Birmingham',
    county: '',
    postCode: 'B15 2DU',
    movedIn: '2017-12-22',
    niNumber: 'DM120190M',
    workPermit: 'Not Needed',
    criminalConvictions: 'No',
    criminalConvictionsDetails: '',
}

export const amiKaur = {
    id: 756398,
    firstName: 'Ami',
    middleNames: '',
    lastName: 'Kaur',
    owner: '# 1',
    number: '07766 597 594',
    email: 'ami@alliance-personnel.com',
    profile: '50%',
    status: 'Active',
    industry: 'Industrial',
    dateOfBirth: '1990-06-19',
    gender: 'Male',
    nationality: '',
    access: [],
    contactPref: [],
    address1: '',
    address2: '',
    address3: '',
    cityTown: '',
    county: '',
    postCode: '',
    movedIn: '',
    niNumber: '',
    permitNeeded: '',
    workPermit: '',
    permitShareCode: '',
    permitNumber: '',
    permitExpiry: '',
    workPermitOther: '',
    criminalConvictions: '',
    criminalConvictionsDetails: '',
}